# Generated by Django 6.0.6 on 2026-07-11 15:33

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prototype', '0005_add_audit_fields_to_projectuserobjectpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(blank=True, max_length=200)),
                ('product_type', models.CharField(blank=True, max_length=200)),
                ('typical_resolution_m', models.FloatField(blank=True, null=True)),
                ('temporal_resolution_days', models.FloatField(blank=True, help_text='Revisit interval in days. Null for static products (e.g. DEM).', null=True)),
                ('band_descriptions', models.JSONField(blank=True, default=list, help_text='Ordered list of band descriptions, e.g. ["Blue (490 nm)", "Green (560 nm)"].')),
                ('url', models.URLField(blank=True, help_text='Link to product documentation.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabelRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, help_text='Blob stored in Django media. Leave blank if the file lives on an external filesystem.', upload_to='raster_data/labels/')),
                ('corpus_path', models.CharField(blank=True, help_text='Path for manifest export. Takes precedence over file.name when set.', max_length=1000)),
                ('n_classes', models.PositiveSmallIntegerField(blank=True, help_text='Number of distinct classes in this file — factual property of the data.', null=True)),
                ('class_names', models.JSONField(blank=True, default=list, help_text='Ordered list of class names — factual property of the data.')),
                ('spatial_bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='WGS-84 bounding box of the label raster.', null=True, srid=4326)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_rasters', to='raster_data.datasource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_rasters', to='prototype.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Label Raster',
                'verbose_name_plural': 'Label Rasters',
                'ordering': ['data_source'],
            },
        ),
        migrations.CreateModel(
            name='RasterDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier used in manifest endpoints.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sampling_seed', models.IntegerField(blank=True, help_text='Random seed used when this dataset was assembled via sample_dataset.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raster_datasets', to='prototype.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raster Dataset',
                'verbose_name_plural': 'Raster Datasets',
                'ordering': ['-modified_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetSceneMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(choices=[('train', 'Train'), ('val', 'Validation'), ('test', 'Test')], max_length=5)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_memberships', to='raster_data.rasterdataset')),
            ],
            options={
                'verbose_name': 'Dataset Scene Membership',
                'verbose_name_plural': 'Dataset Scene Memberships',
            },
        ),
        migrations.CreateModel(
            name='DatasetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(choices=[('train', 'Train'), ('val', 'Validation'), ('test', 'Test')], max_length=5)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_memberships', to='raster_data.rasterdataset')),
            ],
            options={
                'verbose_name': 'Dataset Membership',
                'verbose_name_plural': 'Dataset Memberships',
            },
        ),
        migrations.CreateModel(
            name='RasterScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, help_text='Blob stored in Django media. Leave blank if the file lives on an external filesystem.', upload_to='raster_data/scenes/')),
                ('corpus_path', models.CharField(blank=True, help_text='Path for manifest export. Takes precedence over file.name when set.', max_length=1000)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('n_bands', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resolution_m', models.FloatField(blank=True, help_text='Actual ground sampling distance of this file in metres.', null=True)),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('crs', models.CharField(blank=True, help_text='Coordinate reference system, e.g. "EPSG:32632".', max_length=50)),
                ('spatial_bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='WGS-84 bounding box of the scene.', null=True, srid=4326)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raster_scenes', to='raster_data.datasource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raster_scenes', to='prototype.project')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raster Scene',
                'verbose_name_plural': 'Raster Scenes',
                'ordering': ['-acquisition_date', 'data_source'],
            },
        ),
        migrations.AddField(
            model_name='rasterdataset',
            name='scenes',
            field=models.ManyToManyField(blank=True, related_name='datasets_as_scene', through='raster_data.DatasetSceneMembership', to='raster_data.rasterscene'),
        ),
        migrations.AddField(
            model_name='datasetscenemembership',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_memberships', to='raster_data.rasterscene'),
        ),
        migrations.CreateModel(
            name='SceneLabelPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('valid_pixel_fraction', models.FloatField(blank=True, help_text='Fraction of non-NoData pixels in the label — factual property precomputed at registration.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_pairs', to='raster_data.labelraster')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_pairs', to='raster_data.rasterscene')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scene-Label Pair',
                'verbose_name_plural': 'Scene-Label Pairs',
                'ordering': ['scene', 'label'],
                'unique_together': {('scene', 'label')},
            },
        ),
        migrations.AddField(
            model_name='rasterdataset',
            name='pairs',
            field=models.ManyToManyField(blank=True, related_name='datasets', through='raster_data.DatasetMembership', to='raster_data.scenelabelpair'),
        ),
        migrations.AddField(
            model_name='datasetmembership',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_memberships', to='raster_data.scenelabelpair'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetscenemembership',
            unique_together={('dataset', 'scene')},
        ),
        migrations.AlterUniqueTogether(
            name='datasetmembership',
            unique_together={('dataset', 'pair')},
        ),
    ]
