# Generated by Django 6.0.6 on 2026-07-21 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster_data', '0002_simplify_to_three_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterscene',
            name='spatial_bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='WGS-84 bounding box of the raster.', null=True, srid=4326),
        ),
    ]
