# Generated by Django 6.0.6 on 2026-06-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_alter_project_options_alter_researchgroup_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Team members with working access to this project. Members automatically receive view, add, and change permissions. Delete access must be granted explicitly via the Permissions tab.', related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
