# Generated by Django 6.0.6 on 2026-06-10 21:42

from django.db import migrations, models


def fill_null_fields(apps, schema_editor):
    Project = apps.get_model('prototype', 'Project')
    Project.objects.filter(description__isnull=True).update(description='')
    Project.objects.filter(subtitle__isnull=True).update(subtitle='')
    Researcher = apps.get_model('prototype', 'Researcher')
    Researcher.objects.filter(orcid__isnull=True).update(orcid='')


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_add_members_to_project'),
    ]

    operations = [
        migrations.RunPython(fill_null_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='orcid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
