# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="Country name", max_length=100, null=True),
                ),
                (
                    "iso_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-3 code",
                        max_length=3,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, help_text="Country borders", null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExposureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "main_type",
                    models.CharField(
                        choices=[
                            ("B", "Borehole"),
                            ("E", "Excavation"),
                            ("O", "Outcrop"),
                        ],
                        max_length=10,
                    ),
                ),
                ("abbreviation", models.CharField(max_length=5)),
                ("name_ger", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("identifier", models.IntegerField()),
                ("token", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("depth_top", models.FloatField(blank=True, null=True)),
                ("depth_bottom", models.FloatField(blank=True, null=True)),
                (
                    "structure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ein", "Single grain structure"),
                            ("kit", "Cemented structure"),
                            ("koh", "Coherent structure"),
                            ("ris", "Fissured structure"),
                            ("sau", "Columnar structure"),
                            ("shi", "Layered structure"),
                            ("kru", "Crumb structure"),
                            ("sub", "Subangular blocky structure"),
                            ("pol", "Angular blocky structure"),
                            ("pri", "Prismatic structure"),
                            ("pla", "Platy structure"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "fine_soil_field",
                    models.CharField(
                        blank=True,
                        help_text="Finger test for soil texture",
                        max_length=6,
                        null=True,
                        verbose_name="Fine soil",
                    ),
                ),
                (
                    "munsell_hue_value",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.StepValueValidator(0.5),
                        ],
                    ),
                ),
                (
                    "munsell_hue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("R", "R"),
                            ("Y", "Y"),
                            ("B", "B"),
                            ("P", "P"),
                            ("YR", "YR"),
                            ("GY", "GY"),
                            ("BG", "BG"),
                            ("PB", "PB"),
                            ("RP", "RP"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "munsell_value",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.StepValueValidator(0.5),
                        ],
                    ),
                ),
                (
                    "munsell_chroma",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                            django.core.validators.StepValueValidator(0.5),
                        ],
                    ),
                ),
                (
                    "calcite",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.StepValueValidator(0.5),
                        ],
                    ),
                ),
                (
                    "secondary_calcite",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Project Data"),
                            ("literature", "Literature Data"),
                        ],
                        default="internal",
                        help_text="Source of the location data",
                        max_length=10,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Add a unique identifier to your location.",
                        max_length=80,
                    ),
                ),
                ("date_of_record", models.DateField(blank=True, null=True)),
                (
                    "easting",
                    models.FloatField(blank=True, help_text="in decimal degrees.", null=True),
                ),
                (
                    "northing",
                    models.FloatField(blank=True, help_text="in decimal degrees.", null=True),
                ),
                ("srid", models.IntegerField(default=4326, help_text="EPSG code")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, help_text="in meters above sea level", null=True),
                ),
                (
                    "liner",
                    models.BooleanField(
                        default=False,
                        help_text="Was the location drilled using a closed liner?",
                    ),
                ),
                (
                    "sampling",
                    models.BooleanField(default=False, help_text="Were samples taken at the location?"),
                ),
                ("gradient_upslope", models.FloatField(blank=True, null=True)),
                ("gradient_downslope", models.FloatField(blank=True, null=True)),
                (
                    "slope_aspect",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(360),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "relief_description",
                    models.TextField(
                        blank=True,
                        help_text="Qualitative description of the relief.",
                        null=True,
                    ),
                ),
                (
                    "current_weather_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SU", "Sunny/clear"),
                            ("PC", "Partly cloudy"),
                            ("OV", "Overcast"),
                            ("RA", "Rain"),
                            ("SL", "Sleet"),
                            ("SN", "Snow"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "past_weather_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NM", "No rain the last month"),
                            ("NW", "No rain in the last week"),
                            ("ND", "No rain the last 24 hours"),
                            ("RD", "Rain but no heavy rain the last 24 hours"),
                            (
                                "RH",
                                "Heavy rain for some days or excessive rain in the last 24 hours",
                            ),
                            ("RE", "Extremely rainy or snow melting"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Location",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Province/state name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, help_text="Province borders", null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("identifier", models.CharField(max_length=40, unique=True)),
                ("igsn", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=40, null=True)),
                ("material", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "weight",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "depth_top",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Top depth in cm. For literature data with only midpoint depth, enter the same value in both top and bottom fields.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "depth_bottom",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Bottom depth in cm. For literature data with only midpoint depth, enter the same value in both top and bottom fields.",
                        max_digits=6,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SampleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        help_text="A short, unique identifier for the sample type.",
                        max_length=35,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="A short, abbreviated label.", max_length=5),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The creation timestamp, automatically set.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("label", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudyArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("label", models.CharField(max_length=20)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
                ),
                (
                    "climate_koeppen",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "A: Tropical climates",
                                [
                                    ("Af", "Tropical rainforest climate"),
                                    (
                                        "Aw",
                                        "Tropical savanna climate with dry-winter characteristics",
                                    ),
                                    (
                                        "As",
                                        "Tropical savanna climate with dry-summer characteristics",
                                    ),
                                    ("Am", "Tropical monsoon climate"),
                                ],
                            ),
                            (
                                "B: Dry climates",
                                [
                                    ("BWh", "Hot arid climate"),
                                    ("BWc", "Cold arid climate"),
                                    ("BSh", "Hot semi-arid climate"),
                                    ("BSc", "Cold semi-arid climate"),
                                ],
                            ),
                            (
                                "C: Temperate climates",
                                [
                                    ("Csa", "Mediterranean hot summer climate"),
                                    ("Csb", "Mediterranean warm/cool summer climate"),
                                    ("Csc", "Mediterranean cold summer climate"),
                                    ("Cfa", "Humid subtropical climate"),
                                    ("Cfb", "Oceanic climate"),
                                    ("Cfc", "Subpolar oceanic climate"),
                                    ("Cwa", "Dry-winter humid subtropical climate"),
                                    ("Cwb", "Dry-winter subtropical highland climate"),
                                    ("Cwc", "Dry-winter subpolar oceanic climate"),
                                ],
                            ),
                            (
                                "D: Continental climates",
                                [
                                    ("Dfa", "Hot-summer humid continental climate"),
                                    ("Dfb", "Warm-summer humid continental climate"),
                                    ("Dfc", "Subarctic climate"),
                                    ("Dfd", "Extremely cold subarctic climate"),
                                    (
                                        "Dwa",
                                        "Monsoon-influenced hot-summer humid continental climate",
                                    ),
                                    (
                                        "Dwb",
                                        "Monsoon-influenced warm-summer humid continental climate",
                                    ),
                                    ("Dwc", "Monsoon-influenced subarctic climate"),
                                    (
                                        "Dwd",
                                        "Monsoon-influenced extremely cold subarctic climate",
                                    ),
                                    (
                                        "Dsa",
                                        "Mediterranean-influenced hot-summer humid continental climate",
                                    ),
                                    (
                                        "Dsb",
                                        "Mediterranean-influenced warm-summer humid continental climate",
                                    ),
                                    (
                                        "Dsc",
                                        "Mediterranean-influenced subarctic climate",
                                    ),
                                    (
                                        "Dsd",
                                        "Mediterranean-influenced extremely cold subarctic climate",
                                    ),
                                ],
                            ),
                            (
                                "E: Polar and alpine climates",
                                [("ET", "Tundra climate"), ("EF", "Ice cap climate")],
                            ),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "ecozone_schultz",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TYR", "Tropics with year-round rain"),
                            ("TSR", "Tropics with summer rain"),
                            ("TSD", "Dry Tropics and subtropics"),
                            ("SYR", "Subtropics with year-round rain"),
                            (
                                "SWR",
                                "Subtropics with winter rain (Mediterranean climate)",
                            ),
                            ("MHU", "Humid mid-latitudes"),
                            ("MDR", "Dry mid-latitudes"),
                            ("BOR", "Boreal zone"),
                            ("POS", "Polar-subpolar zone"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Study area",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("word", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, null=True, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("identifier", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=250)),
                (
                    "multiline",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("label", models.CharField(max_length=20, unique=True)),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="Starting date"),
                ),
                (
                    "date_end",
                    models.DateField(blank=True, null=True, verbose_name="Ending date"),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Temperate climates",
                                [
                                    ("SP", "Spring"),
                                    ("SU", "Summer"),
                                    ("AU", "Autumn"),
                                    ("WI", "Winter"),
                                ],
                            ),
                            (
                                "Monsoonal climates",
                                [("WS", "Wet season"), ("DS", "Dry season")],
                            ),
                            (
                                "Equatorial climates",
                                [("NS", "No significant seasonality for plant growth")],
                            ),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
