# Generated by Django 6.0.6 on 2026-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field_data", "0004_alter_location_options_alter_studyarea_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="gps_accuracy",
            field=models.FloatField(
                blank=True,
                help_text="Horizontal accuracy of the GPS measurement in meters.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="positioning_method",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Centimeter-level",
                        [
                            ("rtk_gnss", "RTK GNSS"),
                            ("total_station", "Total Station / Theodolite"),
                        ],
                    ),
                    ("Submeter-level", [("gnss_rover", "GNSS Rover (survey-grade)")]),
                    (
                        "Meter-level",
                        [
                            ("handheld_gps", "Handheld GPS"),
                            ("smartphone", "Smartphone"),
                        ],
                    ),
                    (
                        "Low accuracy",
                        [
                            ("map_digitized", "Topographic map / digitized"),
                            ("estimated", "Estimated / literature"),
                        ],
                    ),
                ],
                help_text="Device or method used to determine the coordinates.",
                max_length=20,
                null=True,
            ),
        ),
    ]
