# Generated by Django 6.0.6 on 2026-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field_data", "0005_location_gps_accuracy_positioning_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("Sampling", [("sampling_location", "Sampling Location")]),
                    (
                        "Infrastructure / Logistics",
                        [
                            ("camp", "Camp / Base camp"),
                            ("road_access", "Road access point"),
                            ("infrastructure", "Infrastructure"),
                        ],
                    ),
                    (
                        "Scientific",
                        [
                            ("weather_station", "Weather station"),
                            ("survey_point", "Survey point"),
                            ("observation", "Observation point"),
                        ],
                    ),
                    ("Other", [("other", "Other")]),
                ],
                default="sampling_location",
                help_text="Category of this location.",
                max_length=30,
            ),
        ),
    ]
