# Generated by Django 6.0.6 on 2026-06-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0006_location_type'),
        ('prototype', '0004_alter_project_description_alter_project_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, help_text="Required for all locations. For general-purpose locations (e.g. weather stations) shared across projects, assign to a dedicated 'Shared Resources' project.", null=True, on_delete=django.db.models.deletion.RESTRICT, to='prototype.project'),
        ),
    ]
