# Generated by Django 6.0.6 on 2026-06-29 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('field_data', '0007_alter_location_project'),
        ('prototype', '0004_alter_project_description_alter_project_subtitle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterField(
            model_name='location',
            name='easting',
            field=models.FloatField(blank=True, help_text='X coordinate — longitude in decimal degrees (EPSG:4326) or easting in metres (UTM).', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='northing',
            field=models.FloatField(blank=True, help_text='Y coordinate — latitude in decimal degrees (EPSG:4326) or northing in metres (UTM).', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='srid',
            field=models.IntegerField(default=4326, help_text='EPSG code — e.g. 4326 (WGS-84 decimal degrees), 32632 (UTM zone 32N), 32633 (UTM zone 33N).'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('slug',), name='unique_tag_slug_when_not_null'),
        ),
    ]
