# Generated by Django 6.0.6 on 2026-06-29 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0008_tag_slug_partial_unique'),
        ('prototype', '0004_alter_project_description_alter_project_subtitle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.AlterField(
            model_name='sample',
            name='identifier',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('project', 'identifier'), name='unique_sample_identifier_per_project'),
        ),
    ]
