# Generated by Django 6.0.6 on 2026-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0009_sample_identifier_unique_per_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', help_text='Review status of the sample.', max_length=20),
        ),
    ]
