# Generated by Django 6.0.6 on 2026-06-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0010_add_sample_status'),
        ('prototype', '0004_alter_project_description_alter_project_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('project', 'label')},
        ),
    ]
