# Generated by Django 6.0.6 on 2026-06-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0011_campaign_label_unique_per_project'),
        ('prototype', '0004_alter_project_description_alter_project_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyarea',
            unique_together={('project', 'label')},
        ),
    ]
