# Generated by Django 6.0.6 on 2026-06-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0012_studyarea_label_unique_per_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('location', 'identifier')},
        ),
    ]
