# Generated by Django 6.0.6 on 2026-07-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('field_data', '0013_layer_identifier_unique_per_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(help_text='Photo, sketch, or scanned field note.', upload_to='field_photos/')),
                ('caption', models.CharField(blank=True, help_text='Short description of the photo or sketch.', max_length=200)),
                ('taken_at', models.DateTimeField(blank=True, help_text='When the photo was taken in the field.', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field photo',
                'verbose_name_plural': 'Field photos',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='field_data__content_ceb50b_idx')],
            },
        ),
    ]
