# Generated by Django 6.0.6 on 2026-08-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_data', '0014_fieldphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
    ]
