# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Accessories",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("token", models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Firmware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("installation_date", models.DateField()),
                ("changelog", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, max_length=40, null=True)),
                ("token", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CHEM", "Geochemical"),
                            ("PHY", "Geophysical"),
                            ("CHRO", "Chronological"),
                        ],
                        default="CHEM",
                        max_length=4,
                    ),
                ),
                (
                    "laboratory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PHY", "Phy.-Geo. Laboratory"),
                            ("CLL", "Cologne Luminescence Laboratory"),
                            ("EX", "External"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccessoryParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=50)),
                ("parameter_name", models.CharField(max_length=50)),
                ("parameter_value", models.CharField(max_length=100)),
                (
                    "parameter_unit",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "accessory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.accessory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("date", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
