# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("laboratory", "0001_initial"),
        ("prototype", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calibration",
            name="researcher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="prototype.researcher",
            ),
        ),
        migrations.AddField(
            model_name="calibration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calibration",
            name="device",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="laboratory.device"),
        ),
        migrations.AddField(
            model_name="accessory",
            name="device",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="laboratory.device"),
        ),
        migrations.AddField(
            model_name="firmware",
            name="device",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="laboratory.device"),
        ),
        migrations.AddField(
            model_name="device",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="laboratory.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="method",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="laboratory.device",
            ),
        ),
    ]
