# Generated by Django 6.0.6 on 2026-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_calibration_options_calibration_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accessoryparameter',
            name='parameter_unit',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='changelog',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='method',
            name='laboratory',
            field=models.CharField(blank=True, choices=[('PHY', 'Phy.-Geo. Laboratory'), ('CLL', 'Cologne Luminescence Laboratory'), ('EX', 'External')], max_length=4),
        ),
        migrations.AlterField(
            model_name='method',
            name='token',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
