# Generated by Django 6.0.6 on 2026-06-10 21:42

from django.db import migrations, models


def fill_null_fields(apps, schema_editor):
    Accessory = apps.get_model('laboratory', 'Accessory')
    Accessory.objects.filter(description__isnull=True).update(description='')
    AccessoryParameter = apps.get_model('laboratory', 'AccessoryParameter')
    AccessoryParameter.objects.filter(parameter_unit__isnull=True).update(parameter_unit='')
    Calibration = apps.get_model('laboratory', 'Calibration')
    Calibration.objects.filter(remarks__isnull=True).update(remarks='')
    Device = apps.get_model('laboratory', 'Device')
    Device.objects.filter(description__isnull=True).update(description='')
    Device.objects.filter(token__isnull=True).update(token='')
    Firmware = apps.get_model('laboratory', 'Firmware')
    Firmware.objects.filter(changelog__isnull=True).update(changelog='')
    Manufacturer = apps.get_model('laboratory', 'Manufacturer')
    Manufacturer.objects.filter(website__isnull=True).update(website='')
    Method = apps.get_model('laboratory', 'Method')
    Method.objects.filter(description__isnull=True).update(description='')
    Method.objects.filter(laboratory__isnull=True).update(laboratory='')
    Method.objects.filter(token__isnull=True).update(token='')


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_calibration_options_calibration_modified_at_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_null_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accessoryparameter',
            name='parameter_unit',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='changelog',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='method',
            name='laboratory',
            field=models.CharField(blank=True, choices=[('PHY', 'Phy.-Geo. Laboratory'), ('CLL', 'Cologne Luminescence Laboratory'), ('EX', 'External')], max_length=4),
        ),
        migrations.AlterField(
            model_name='method',
            name='token',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
