# Generated by Django 6.0.6 on 2026-08-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_alter_accessory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['device', 'name'], 'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='firmware',
            options={'ordering': ['device', 'version']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['name']},
        ),
    ]
