# Generated by Django 6.0.6 on 2026-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerun",
            name="dump_format",
            field=models.CharField(
                choices=[
                    ("custom", "Custom (pg_dump -Fc, compressed — recommended)"),
                    ("plain", "Plain SQL (pg_dump -Fp, human-readable)"),
                ],
                default="custom",
                help_text="Output format for backup jobs (ignored for other job types).",
                max_length=10,
            ),
        ),
    ]
