# Generated by Django 6.0.6 on 2026-06-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0002_maintenancerun_dump_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_type", models.CharField(max_length=50)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="orchestration.maintenancerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrity Issue",
                "verbose_name_plural": "Integrity Issues",
            },
        ),
    ]
