# Generated by Django 6.0.6 on 2026-08-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0003_integrityissue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrityissue',
            options={'ordering': ['run', 'id'], 'verbose_name': 'Integrity Issue', 'verbose_name_plural': 'Integrity Issues'},
        ),
    ]
