# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("keyword", models.CharField(max_length=250, unique=True)),
                (
                    "keyword_ger",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("title", models.CharField(max_length=250)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("published", models.BooleanField(blank=True, null=True)),
                ("abstract", models.TextField()),
                ("journal", models.CharField(blank=True, max_length=250, null=True)),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
                ("pages", models.CharField(blank=True, max_length=250, null=True)),
                ("publisher", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "location_of_publication",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Monography", "Monography"),
                            ("Master's thesis", "Master's thesis"),
                            ("Bachelor's thesis", "Bachelor's thesis"),
                            ("PhD thesis", "PhD thesis"),
                            ("Paper", "Paper"),
                            ("Chapter", "Chapter"),
                            ("Collection", "Collection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("doi", models.URLField(blank=True, max_length=50, null=True)),
                ("issn", models.IntegerField(blank=True, null=True)),
                ("isbn_print", models.CharField(blank=True, max_length=50, null=True)),
                ("isbn_online", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "how_to_cite",
                    models.CharField(blank=True, max_length=350, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lead_author",
                        to="bibliography.author",
                    ),
                ),
                (
                    "parent_publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="bibliography.reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference",
                "verbose_name_plural": "References",
                "ordering": ["-year", "title"],
            },
        ),
    ]
