# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bibliography", "0001_initial"),
        ("prototype", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="project",
            field=models.ManyToManyField(blank=True, to="prototype.project"),
        ),
        migrations.AddField(
            model_name="reference",
            name="second_author",
            field=models.ManyToManyField(
                related_name="second_author", to="bibliography.author"
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="supervisor",
            field=models.ManyToManyField(
                blank=True, related_name="supervisor", to="bibliography.author"
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referencekeyword",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referencekeyword",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, to="bibliography.referencekeyword"
            ),
        ),
    ]
