# Generated by Django 6.0.1 on 2026-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bibliography",
            "0003_alter_author_options_alter_referencekeyword_options_and_more",
        ),
        (
            "prototype",
            "0002_alter_project_options_alter_researchgroup_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="isbn_online",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="ISBN Online"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="isbn_print",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="ISBN Print"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="issn",
            field=models.IntegerField(blank=True, null=True, verbose_name="ISSN"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="project",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select a project, provided that a unique one can be assigned to the publication.",
                to="prototype.project",
            ),
        ),
    ]
