# Generated by Django 6.0.6 on 2026-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0004_alter_reference_isbn_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='how_to_cite',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='reference',
            name='isbn_online',
            field=models.CharField(blank=True, max_length=50, verbose_name='ISBN Online'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='isbn_print',
            field=models.CharField(blank=True, max_length=50, verbose_name='ISBN Print'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='journal',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='reference',
            name='location_of_publication',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pages',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publisher',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='referencekeyword',
            name='keyword_ger',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
