# Generated by Django 6.0.6 on 2026-06-10 21:42

from django.db import migrations, models


def fill_null_fields(apps, schema_editor):
    Reference = apps.get_model('bibliography', 'Reference')
    Reference.objects.filter(doi__isnull=True).update(doi='')
    Reference.objects.filter(how_to_cite__isnull=True).update(how_to_cite='')
    Reference.objects.filter(isbn_online__isnull=True).update(isbn_online='')
    Reference.objects.filter(isbn_print__isnull=True).update(isbn_print='')
    Reference.objects.filter(journal__isnull=True).update(journal='')
    Reference.objects.filter(location_of_publication__isnull=True).update(location_of_publication='')
    Reference.objects.filter(pages__isnull=True).update(pages='')
    Reference.objects.filter(publisher__isnull=True).update(publisher='')
    ReferenceKeyword = apps.get_model('bibliography', 'ReferenceKeyword')
    ReferenceKeyword.objects.filter(keyword_ger__isnull=True).update(keyword_ger='')


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0004_alter_reference_isbn_online_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_null_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='how_to_cite',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='reference',
            name='isbn_online',
            field=models.CharField(blank=True, max_length=50, verbose_name='ISBN Online'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='isbn_print',
            field=models.CharField(blank=True, max_length=50, verbose_name='ISBN Print'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='journal',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='reference',
            name='location_of_publication',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pages',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publisher',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='referencekeyword',
            name='keyword_ger',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
