# Generated by Django 6.0.6 on 2026-08-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0005_alter_reference_doi_alter_reference_how_to_cite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='issn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ISSN'),
            preserve_default=False,
        ),
    ]
