# Generated by Django 6.0.6 on 2026-06-25 19:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("field_data", "0007_alter_location_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Landform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Polygon boundary of this landform region.",
                        srid=4326,
                    ),
                ),
                (
                    "brid_nam",
                    models.CharField(
                        blank=True,
                        help_text="Full hierarchical name (BridNam), e.g. 'Canadian Archipelago and Greenland Northern Mountains'.",
                        max_length=500,
                    ),
                ),
                (
                    "name_str",
                    models.CharField(
                        blank=True,
                        help_text="Short region name (NameStr).",
                        max_length=255,
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True,
                        help_text="Division within the continent.",
                        max_length=255,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        help_text="Province within the division.",
                        max_length=255,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section within the province (often empty).",
                        max_length=255,
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        blank=True, help_text="Continent name.", max_length=100
                    ),
                ),
                (
                    "murphy_code",
                    models.CharField(
                        blank=True,
                        help_text="Murphy landform code, e.g. 'SPwd'.",
                        max_length=10,
                    ),
                ),
                (
                    "structure",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Structural geology code.",
                        null=True,
                    ),
                ),
                (
                    "moist_dry",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Moisture regime code.",
                        null=True,
                    ),
                ),
                (
                    "topog",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Topography code.", null=True
                    ),
                ),
                (
                    "process",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Dominant geomorphological process code.",
                        null=True,
                    ),
                ),
                (
                    "glaciate",
                    models.CharField(
                        blank=True,
                        help_text="Glaciation history, e.g. 'Wisconsin Wurm'.",
                        max_length=100,
                    ),
                ),
                (
                    "volcanism",
                    models.CharField(
                        blank=True,
                        help_text="Volcanism description.",
                        max_length=255,
                    ),
                ),
                (
                    "volc_name",
                    models.CharField(
                        blank=True,
                        help_text="Volcanic feature name (VolcName).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "si_vol_num",
                    models.CharField(
                        blank=True,
                        help_text="Smithsonian Institution volcano number (SI_Vol_Num).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "vol_reg",
                    models.CharField(
                        blank=True,
                        help_text="Volcanic region (Vol_Reg).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "vol_prov",
                    models.CharField(
                        blank=True,
                        help_text="Volcanic province (Vol_Prov).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "plate_1",
                    models.CharField(
                        blank=True,
                        help_text="Primary tectonic plate.",
                        max_length=100,
                    ),
                ),
                ("plate_2", models.CharField(blank=True, max_length=100)),
                ("plate_3", models.CharField(blank=True, max_length=100)),
                ("plate_4", models.CharField(blank=True, max_length=100)),
                ("plate_5", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "area_geo",
                    models.FloatField(
                        blank=True,
                        help_text="Geographic area from source dataset (AREA_GEO).",
                        null=True,
                    ),
                ),
                (
                    "shape_length",
                    models.FloatField(
                        blank=True,
                        help_text="Shape length from source dataset (Shape_Length).",
                        null=True,
                    ),
                ),
                (
                    "shape_area",
                    models.FloatField(
                        blank=True,
                        help_text="Shape area from source dataset (Shape_Area).",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text='Dataset version, e.g. "Murphy Landform Regions ESRI 2022".',
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Landform",
                "verbose_name_plural": "Landforms",
                "ordering": ["continent", "division", "province"],
            },
        ),
    ]
