# Generated by Django 6.0.6 on 2026-06-25 19:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("field_data", "0007_alter_location_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Geomorphon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Polygon extent of this terrain form class.",
                        srid=4326,
                    ),
                ),
                (
                    "geomorphon_class",
                    models.IntegerField(
                        choices=[
                            (1, "Flat"),
                            (2, "Peak"),
                            (3, "Ridge"),
                            (4, "Shoulder"),
                            (5, "Spur"),
                            (6, "Slope"),
                            (7, "Hollow"),
                            (8, "Footslope"),
                            (9, "Valley"),
                            (10, "Pit"),
                        ],
                        help_text="Terrain form class (1–10) after Jasiewicz & Stepinski (2013).",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text='Source DEM and tool, e.g. "SRTM 30m via GRASS r.geomorphon".',
                        max_length=255,
                    ),
                ),
                (
                    "resolution_m",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pixel resolution of the source DEM in metres.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: StudyArea this geomorphon layer was derived for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geomorphons",
                        to="field_data.studyarea",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Geomorphon",
                "verbose_name_plural": "Geomorphons",
                "ordering": ["geomorphon_class"],
            },
        ),
        migrations.CreateModel(
            name="Landform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Polygon boundary of this landform region.",
                        srid=4326,
                    ),
                ),
                (
                    "brid_nam",
                    models.CharField(
                        blank=True,
                        help_text="Full hierarchical name (BridNam), e.g. 'Canadian Archipelago and Greenland Northern Mountains'.",
                        max_length=500,
                    ),
                ),
                (
                    "name_str",
                    models.CharField(
                        blank=True,
                        help_text="Short region name (NameStr).",
                        max_length=255,
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True,
                        help_text="Division within the continent.",
                        max_length=255,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        help_text="Province within the division.",
                        max_length=255,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section within the province (often empty).",
                        max_length=255,
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        blank=True, help_text="Continent name.", max_length=100
                    ),
                ),
                (
                    "murphy_code",
                    models.CharField(
                        blank=True,
                        help_text="Murphy landform code, e.g. 'SPwd'.",
                        max_length=10,
                    ),
                ),
                (
                    "structure",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Structural geology code.",
                        null=True,
                    ),
                ),
                (
                    "moist_dry",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Moisture regime code.",
                        null=True,
                    ),
                ),
                (
                    "topog",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Topography code.", null=True
                    ),
                ),
                (
                    "process",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Dominant geomorphological process code.",
                        null=True,
                    ),
                ),
                (
                    "glaciate",
                    models.CharField(
                        blank=True,
                        help_text="Glaciation history, e.g. 'Wisconsin Wurm'.",
                        max_length=100,
                    ),
                ),
                (
                    "volcanism",
                    models.CharField(
                        blank=True,
                        help_text="Volcanism description.",
                        max_length=255,
                    ),
                ),
                (
                    "volc_name",
                    models.CharField(
                        blank=True,
                        help_text="Volcanic feature name (VolcName).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "si_vol_num",
                    models.CharField(
                        blank=True,
                        help_text="Smithsonian Institution volcano number (SI_Vol_Num).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "vol_reg",
                    models.CharField(
                        blank=True,
                        help_text="Volcanic region (Vol_Reg).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "vol_prov",
                    models.CharField(
                        blank=True,
                        help_text="Volcanic province (Vol_Prov).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "plate_1",
                    models.CharField(
                        blank=True,
                        help_text="Primary tectonic plate.",
                        max_length=100,
                    ),
                ),
                ("plate_2", models.CharField(blank=True, max_length=100)),
                ("plate_3", models.CharField(blank=True, max_length=100)),
                ("plate_4", models.CharField(blank=True, max_length=100)),
                ("plate_5", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "area_geo",
                    models.FloatField(
                        blank=True,
                        help_text="Geographic area from source dataset (AREA_GEO).",
                        null=True,
                    ),
                ),
                (
                    "shape_length",
                    models.FloatField(
                        blank=True,
                        help_text="Shape length from source dataset (Shape_Length).",
                        null=True,
                    ),
                ),
                (
                    "shape_area",
                    models.FloatField(
                        blank=True,
                        help_text="Shape area from source dataset (Shape_Area).",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text='Dataset version, e.g. "Murphy Landform Regions ESRI 2022".',
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Landform",
                "verbose_name_plural": "Landforms",
                "ordering": ["continent", "division", "province"],
            },
        ),
        migrations.CreateModel(
            name="WorldCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Polygon extent of this land cover class.",
                        srid=4326,
                    ),
                ),
                (
                    "landcover_class",
                    models.IntegerField(
                        choices=[
                            (10, "Tree cover"),
                            (20, "Shrubland"),
                            (30, "Grassland"),
                            (40, "Cropland"),
                            (50, "Built-up"),
                            (60, "Bare / sparse vegetation"),
                            (70, "Snow and Ice"),
                            (80, "Permanent water bodies"),
                            (90, "Herbaceous wetland"),
                            (95, "Mangroves"),
                            (100, "Moss and lichen"),
                        ],
                        help_text="ESA WorldCover class code (10–100).",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Product year: 2020 (v100) or 2021 (v200)."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="ESA WorldCover v200 2021",
                        help_text="Dataset version string.",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WorldCover",
                "verbose_name_plural": "WorldCover",
                "ordering": ["landcover_class"],
            },
        ),
    ]
