# Generated by Django 6.0.1 on 2026-01-27 14:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GridCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "grid_id",
                    models.CharField(
                        help_text="The unique, human-readable identifier for this grid cell (S2 token).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "s2_token",
                    models.CharField(
                        db_index=True,
                        help_text="The S2 cell token (e.g., '1/123456789abcdef').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "s2_level",
                    models.IntegerField(
                        db_index=True,
                        help_text="The S2 cell level (0-30). Higher levels mean smaller cells.",
                    ),
                ),
                (
                    "footprint",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="The exact geographic polygon of this grid cell.",
                        srid=4326,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grid Cells",
                "ordering": ["grid_id"],
            },
        ),
        migrations.CreateModel(
            name="DataCube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cell",
                    models.OneToOneField(
                        help_text="Die Grid-Zelle, zu der dieser DataCube gehört.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datacube",
                        to="morphogrid.gridcell",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Data Cubes",
                "ordering": ["cell__grid_id"],
            },
        ),
        migrations.CreateModel(
            name="CubeLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("s2_b01", "Sentinel-2 Band 1 (Coastal)"),
                            ("s2_b02", "Sentinel-2 Band 2 (Blue)"),
                            ("s2_b03", "Sentinel-2 Band 3 (Green)"),
                            ("s2_b04", "Sentinel-2 Band 4 (Red)"),
                            ("s2_b05", "Sentinel-2 Band 5 (Red Edge 1)"),
                            ("s2_b06", "Sentinel-2 Band 6 (Red Edge 2)"),
                            ("s2_b07", "Sentinel-2 Band 7 (Red Edge 3)"),
                            ("s2_b08", "Sentinel-2 Band 8 (NIR)"),
                            ("s2_b8a", "Sentinel-2 Band 8A (Narrow NIR)"),
                            ("s2_b09", "Sentinel-2 Band 9 (Water Vapor)"),
                            ("s2_b11", "Sentinel-2 Band 11 (SWIR 1)"),
                            ("s2_b12", "Sentinel-2 Band 12 (SWIR 2)"),
                            ("elevation", "Elevation (SRTM)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("layer_file", models.FileField(upload_to="cubes/%Y/%m/")),
                ("acquisition_date", models.DateField()),
                ("acquisition_group", models.CharField(blank=True, max_length=100)),
                ("resolution_m", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="morphogrid.datacube",
                    ),
                ),
            ],
            options={
                "db_table": "datacubes_layer",
                "indexes": [
                    models.Index(
                        fields=["acquisition_group"],
                        name="datacubes_l_acquisi_10137b_idx",
                    ),
                    models.Index(fields=["layer_type"], name="datacubes_l_layer_t_b6fe61_idx"),
                ],
                "unique_together": {("cube", "layer_type", "acquisition_date")},
            },
        ),
    ]
