# Generated by Django 6.0.1 on 2026-01-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("morphogrid", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gridcell",
            name="footprint",
        ),
    ]
