# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import analysis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="analysis/algorithms/"
                    ),
                ),
                (
                    "programming_language",
                    models.CharField(
                        choices=[
                            ("Python", "Python"),
                            ("R", "R"),
                            ("MATLAB", "MATLAB"),
                            ("Julia", "Julia"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenericMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("sample_weight", models.FloatField(blank=True, null=True)),
                ("value", models.FloatField(blank=True, null=True)),
                ("error", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GrainSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("sample_weight", models.FloatField(blank=True, null=True)),
                (
                    "sample_concentration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Sample concentration [%]"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("L", "Laser diffraction"),
                            ("C", "Camsizer"),
                            ("S", "Sieves"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "classes",
                    models.JSONField(
                        default=analysis.models.default_classes,
                        help_text="This field is for determining the classes of the raw grain size measurement.",
                    ),
                ),
                (
                    "measured_data",
                    models.JSONField(
                        blank=True,
                        help_text="This field contains the raw grain size measurement data.",
                        null=True,
                    ),
                ),
                ("clay", models.FloatField(blank=True, null=True)),
                ("fine_silt", models.FloatField(blank=True, null=True)),
                ("medium_silt", models.FloatField(blank=True, null=True)),
                ("coarse_silt", models.FloatField(blank=True, null=True)),
                ("fine_sand", models.FloatField(blank=True, null=True)),
                ("medium_sand", models.FloatField(blank=True, null=True)),
                ("coarse_sand", models.FloatField(blank=True, null=True)),
                ("mean", models.FloatField(blank=True, null=True)),
                ("mode", models.FloatField(blank=True, null=True)),
                ("median", models.FloatField(blank=True, null=True)),
                (
                    "std",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Standard Deviation"
                    ),
                ),
                (
                    "skew",
                    models.FloatField(blank=True, null=True, verbose_name="Skewness"),
                ),
                ("kurtosis", models.FloatField(blank=True, null=True)),
                (
                    "fwmean",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Folk & Ward Mean"
                    ),
                ),
                (
                    "fwmedian",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Folk & Ward Median"
                    ),
                ),
                (
                    "fwsd",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Folk & Ward Standard Deviation",
                    ),
                ),
                (
                    "fwskew",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Folk & Ward Skewness"
                    ),
                ),
                (
                    "fwkurt",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Folk & Ward Kurtosis"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grain size",
            },
        ),
        migrations.CreateModel(
            name="LuminescenceDating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "laboratory_id",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Laboratory ID",
                    ),
                ),
                (
                    "sample_id_cll",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Sample ID CLL",
                    ),
                ),
                (
                    "mineral",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Quartz", "Quartz"),
                            ("Feldspar", "Feldspar"),
                            ("Polymineral", "Polymineral"),
                            ("Other", "Other"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "dating_approach",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Burial dating", "Burial dating"),
                            ("Exposure dating", "Exposure dating"),
                            ("Other", "Other"),
                        ],
                        max_length=18,
                        null=True,
                    ),
                ),
                (
                    "luminescence_age",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ka",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "age_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ka, 1σ",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        blank=True,
                        help_text="BSL/IRSL/pIRSL/TL/…",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        blank=True, help_text="SAR/MAAD/…", max_length=30, null=True
                    ),
                ),
                (
                    "palaeodose_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy",
                        max_digits=10,
                        null=True,
                        verbose_name="Palaeodose",
                    ),
                ),
                (
                    "palaeodose_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy, 1σ",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dose_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Gy/ka",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "dose_rate_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Gy/ka, 1σ",
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                (
                    "year_of_publication",
                    models.PositiveIntegerField(
                        blank=True,
                        default=2025,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1984),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                    ),
                ),
                (
                    "thesis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BSc", "BSc"),
                            ("MSc", "MSc"),
                            ("PhD", "PhD"),
                            ("None", "None"),
                        ],
                        default="None",
                        max_length=4,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("grain_size_min", models.IntegerField(blank=True, null=True)),
                ("grain_size_max", models.IntegerField(blank=True, null=True)),
                (
                    "aliquot_size",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "aliquot_number_used_for_palaeodose",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "od_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="%",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "od_percent_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="%",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "od_gy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Gy",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "od_gy_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Gy",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "age_model",
                    models.CharField(
                        blank=True,
                        help_text="CAM/MAM/AM/FMM/…",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "beta_source_calibration",
                    models.CharField(
                        blank=True, default="2019-2", max_length=30, null=True
                    ),
                ),
                (
                    "instrumental_beta_source_error",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=7, null=True
                    ),
                ),
                (
                    "uncertainty_beta_source_calibration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "fading_correction",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "g_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="%/dec",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "g_value_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="%/dec",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "Lnat_Lsat_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="L_na/L_sat",
                        max_digits=7,
                        null=True,
                        verbose_name="L_na/L_sat-ratio",
                    ),
                ),
                (
                    "dose_rate_measurement_technique",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dose_rate_calculation_software",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "u_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="ppm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "u_ppm_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="ppm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "th_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="ppm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "th_ppm_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="ppm",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "k_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="%",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "k_percent_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="%",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "water_content_for_dating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="%",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "water_content_for_dating_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="%",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "a_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "a_value_error",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "alpha_dose_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy/ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "alpha_dose_rate_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy/ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "beta_dose_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy/ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "beta_dose_rate_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy/ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "gamma_dose_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy/ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "gamma_dose_rate_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy/ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cosmic_dose_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy/ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cosmic_dose_rate_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gy/ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeasurementSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("datetime", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MicroXRFElementMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "element",
                    models.CharField(
                        choices=[
                            ("Al", "Aluminium (Al)"),
                            ("As", "Arsenic (As)"),
                            ("Ba", "Barium (Ba)"),
                            ("Br", "Bromine (Br)"),
                            ("C", "Carbon (C)"),
                            ("Ca", "Calcium (Ca)"),
                            ("Cl", "Chlorine (Cl)"),
                            ("Co", "Cobalt (Co)"),
                            ("Cr", "Chromium (Cr)"),
                            ("Cu", "Copper (Cu)"),
                            ("Fe", "Iron (Fe)"),
                            ("Hg", "Mercury (Hg)"),
                            ("K", "Potassium (K)"),
                            ("Mg", "Magnesium (Mg)"),
                            ("Mn", "Manganese (Mn)"),
                            ("Mo", "Molybdenum (Mo)"),
                            ("Na", "Sodium (Na)"),
                            ("Ni", "Nickel (Ni)"),
                            ("P", "Phosphorus (P)"),
                            ("Pb", "Lead (Pb)"),
                            ("S", "Sulfur (S)"),
                            ("Se", "Selenium (Se)"),
                            ("Si", "Silicon (Si)"),
                            ("Sn", "Tin (Sn)"),
                            ("Sr", "Strontium (Sr)"),
                            ("Ti", "Titanium (Ti)"),
                            ("V", "Vanadium (V)"),
                            ("Zn", "Zinc (Zn)"),
                            ("Zr", "Zirconium (Zr)"),
                            ("Al2O3", "Aluminium Oxide (Al2O3)"),
                            ("As2O3", "Arsenic Trioxide (As2O3)"),
                            ("BaSO4", "Barium Sulfate (BaSO4)"),
                            ("Br2", "Bromine (Br2)"),
                            ("CaO", "Calcium Oxide (CaO)"),
                            ("Cl2", "Chlorine (Cl2)"),
                            ("CoO", "Cobalt(II) Oxide (CoO)"),
                            ("Cr2O3", "Chromium(III) Oxide (Cr2O3)"),
                            ("CuO", "Copper(II) Oxide (CuO)"),
                            ("Fe2O3", "Iron(III) Oxide (Fe2O3)"),
                            ("HgS", "Mercury Sulfide (HgS)"),
                            ("K2O", "Potassium Oxide (K2O)"),
                            ("MgO", "Magnesium Oxide (MgO)"),
                            ("MoO3", "Molybdenum Trioxide (MoO3)"),
                            ("Na2O", "Sodium Oxide (Na2O)"),
                            ("NiO", "Nickel(II) Oxide (NiO)"),
                            ("P2O5", "Phosphorus Pentoxide (P2O5)"),
                            ("PbO", "Lead(II) Oxide (PbO)"),
                            ("SeO2", "Selenium Dioxide (SeO2)"),
                            ("SiO2", "Silicon Dioxide (SiO2)"),
                            ("SnO2", "Tin(IV) Oxide (SnO2)"),
                            ("SO3", "Sulfur Trioxide (SO3)"),
                            ("SrSO4", "Strontium Sulfate (SrSO4)"),
                            ("TiO2", "Titanium Dioxide (TiO2)"),
                            ("VO2", "Vanadium Dioxide (VO2)"),
                            ("ZnO", "Zinc Oxide (ZnO)"),
                            ("ZrO2", "Zirconium Dioxide (ZrO2)"),
                        ],
                        help_text="Element (e.g. Fe, Mn, Si, ...)",
                        max_length=10,
                    ),
                ),
                (
                    "raster_file",
                    models.FileField(
                        help_text="Pfad zur .tif Rasterdatei",
                        upload_to="microxrf_raster/",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="counts",
                        help_text="Einheit (z.B. counts, ppm, %)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MicroXRFMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "measurement_date",
                    models.DateField(
                        blank=True, help_text="Date of measurement", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=40)),
                ("token", models.CharField(max_length=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("mg/kg", "mg/kg"),
                            ("Percent", "Percent"),
                            ("no dimension", "no dimension"),
                        ],
                        max_length=40,
                        verbose_name="Physical unit",
                    ),
                ),
                ("minimal_limit", models.FloatField(blank=True, null=True)),
                ("maximal_limit", models.FloatField(blank=True, null=True)),
                (
                    "classes",
                    models.JSONField(
                        blank=True,
                        help_text="This field is for determining the classes of unstructured list data.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pollen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(help_text="Name in Latin", max_length=250)),
                ("token", models.CharField(max_length=5)),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="Name in English",
                        max_length=250,
                        null=True,
                        verbose_name="English name",
                    ),
                ),
                (
                    "name_german",
                    models.CharField(
                        blank=True,
                        help_text="Name in German",
                        max_length=250,
                        null=True,
                        verbose_name="German name",
                    ),
                ),
                (
                    "name_nor",
                    models.CharField(
                        blank=True,
                        help_text="Name in Norwegian",
                        max_length=250,
                        null=True,
                        verbose_name="Norwegian name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pollen",
                "verbose_name_plural": "Pollen",
            },
        ),
        migrations.CreateModel(
            name="PollenCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("number", models.IntegerField()),
            ],
            options={
                "verbose_name": "Pollen Count",
                "verbose_name_plural": "Pollen Counts",
            },
        ),
        migrations.CreateModel(
            name="RadiocarbonDating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "lab",
                    models.CharField(
                        choices=[
                            ("Poznań", "Poznań"),
                            ("Beta Analytics", "Beta Analytics"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("lab_id", models.CharField(max_length=30)),
                (
                    "age",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ka",
                        max_digits=8,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RawMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("file", models.FileField(upload_to="analysis/raw_data/")),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RawProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "processed_file",
                    models.FileField(upload_to="analysis/processed_data/"),
                ),
                ("processing_description", models.TextField(blank=True, null=True)),
                ("processing_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Counting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Percent", "Percent"),
                            ("Absolute numbers", "Absolute numbers"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Counting",
                "verbose_name_plural": "Countings",
            },
        ),
    ]
