# Generated by Django 5.2.8 on 2025-12-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0003_initial"),
        ("bibliography", "0001_initial"),
        ("field_data", "0001_initial"),
        ("prototype", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmeasurement",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_raw_data",
                to="prototype.project",
            ),
        ),
        migrations.AddField(
            model_name="rawmeasurement",
            name="researcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_raw_data",
                to="prototype.researcher",
            ),
        ),
        migrations.AddField(
            model_name="rawmeasurement",
            name="sample",
            field=models.ManyToManyField(
                related_name="analysis_raw_data", to="field_data.sample"
            ),
        ),
        migrations.AddField(
            model_name="rawmeasurement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radiocarbondating",
            name="raw_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="analysis_radiocarbon_raw_data",
                to="analysis.rawmeasurement",
            ),
        ),
        migrations.AddField(
            model_name="luminescencedating",
            name="raw_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="analysis_luminescence_datings",
                to="analysis.rawmeasurement",
            ),
        ),
        migrations.AddField(
            model_name="grainsize",
            name="raw_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="generic_grain_sizes",
                to="analysis.rawmeasurement",
            ),
        ),
        migrations.AddField(
            model_name="genericmeasurement",
            name="raw_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="generic_measurements",
                to="analysis.rawmeasurement",
            ),
        ),
        migrations.AddField(
            model_name="counting",
            name="raw_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="analysis_counting_raw_data",
                to="analysis.rawmeasurement",
            ),
        ),
        migrations.AddField(
            model_name="rawprocessing",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rawprocessing",
            name="evaluation_algorithm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_evaluated_data",
                to="analysis.algorithm",
            ),
        ),
        migrations.AddField(
            model_name="rawprocessing",
            name="preparation_algorithm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_processed_data",
                to="analysis.algorithm",
            ),
        ),
        migrations.AddField(
            model_name="rawprocessing",
            name="processed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_processed_data",
                to="prototype.researcher",
            ),
        ),
        migrations.AddField(
            model_name="rawprocessing",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_processed_data",
                to="bibliography.reference",
            ),
        ),
        migrations.AddField(
            model_name="rawprocessing",
            name="raw_measurement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_raw_processing",
                to="analysis.rawmeasurement",
            ),
        ),
        migrations.AddField(
            model_name="rawprocessing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
