# Generated by Django 6.0.1 on 2026-01-27 14:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genericmeasurement",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="luminescencedating",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="measurementseries",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="microxrfelementmap",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="microxrfmeasurement",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="parameter",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="radiocarbondating",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="rawmeasurement",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="rawprocessing",
            options={"ordering": ["-modified_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="counting",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="genericmeasurement",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="grainsize",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="luminescencedating",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="measurementseries",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="microxrfelementmap",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="microxrfmeasurement",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="parameter",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="pollen",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="pollencount",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="radiocarbondating",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="rawmeasurement",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="rawprocessing",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="counting",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="counting",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="genericmeasurement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="genericmeasurement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grainsize",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grainsize",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="age_model",
            field=models.CharField(blank=True, help_text="CAM/MAM/AM/FMM/…", max_length=30),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="aliquot_size",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="beta_source_calibration",
            field=models.CharField(blank=True, default="2019-2", max_length=30),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="dating_approach",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Burial dating", "Burial dating"),
                    ("Exposure dating", "Exposure dating"),
                    ("Other", "Other"),
                ],
                max_length=18,
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="dose_rate_calculation_software",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="dose_rate_measurement_technique",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="laboratory_id",
            field=models.CharField(blank=True, max_length=15, verbose_name="Laboratory ID"),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="mineral",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Quartz", "Quartz"),
                    ("Feldspar", "Feldspar"),
                    ("Polymineral", "Polymineral"),
                    ("Other", "Other"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="protocol",
            field=models.CharField(blank=True, help_text="SAR/MAAD/…", max_length=30),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="sample_id_cll",
            field=models.CharField(blank=True, max_length=15, verbose_name="Sample ID CLL"),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="signal",
            field=models.CharField(blank=True, help_text="BSL/IRSL/pIRSL/TL/…", max_length=30),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="thesis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BSc", "BSc"),
                    ("MSc", "MSc"),
                    ("PhD", "PhD"),
                    ("None", "None"),
                ],
                default="None",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="year_of_publication",
            field=models.PositiveIntegerField(
                blank=True,
                default=2025,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1984),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="measurementseries",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="measurementseries",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="microxrfelementmap",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="microxrfelementmap",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="microxrfmeasurement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="microxrfmeasurement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pollen",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pollen",
            name="name_en",
            field=models.CharField(
                blank=True,
                help_text="Name in English",
                max_length=250,
                verbose_name="English name",
            ),
        ),
        migrations.AlterField(
            model_name="pollen",
            name="name_german",
            field=models.CharField(
                blank=True,
                help_text="Name in German",
                max_length=250,
                verbose_name="German name",
            ),
        ),
        migrations.AlterField(
            model_name="pollen",
            name="name_nor",
            field=models.CharField(
                blank=True,
                help_text="Name in Norwegian",
                max_length=250,
                verbose_name="Norwegian name",
            ),
        ),
        migrations.AlterField(
            model_name="pollen",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pollencount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pollencount",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="radiocarbondating",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="radiocarbondating",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rawmeasurement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rawmeasurement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rawprocessing",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rawprocessing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
