# Generated by Django 6.0.1 on 2026-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_alter_genericmeasurement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="luminescencedating",
            name="aliquot_size",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
