# Generated by Django 6.0.6 on 2026-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_alter_luminescencedating_aliquot_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="grainsize",
            name="gravel",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Gravel (≥ 2000 µm) [%]"
            ),
        ),
        migrations.AddField(
            model_name="grainsize",
            name="source",
            field=models.CharField(
                choices=[
                    ("file", "Imported from file"),
                    ("manual", "Entered manually"),
                ],
                default="manual",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="a_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="a-value",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="a_value_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="a-value error (1σ)",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="age_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="ka, 1σ",
                max_digits=7,
                null=True,
                verbose_name="Age error (1σ) [ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="alpha_dose_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy/ka",
                max_digits=8,
                null=True,
                verbose_name="α dose rate [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="alpha_dose_rate_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy/ka",
                max_digits=8,
                null=True,
                verbose_name="α dose rate error (1σ) [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="beta_dose_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy/ka",
                max_digits=8,
                null=True,
                verbose_name="β dose rate [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="beta_dose_rate_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy/ka",
                max_digits=8,
                null=True,
                verbose_name="β dose rate error (1σ) [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="cosmic_dose_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy/ka",
                max_digits=8,
                null=True,
                verbose_name="Cosmic dose rate [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="cosmic_dose_rate_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy/ka",
                max_digits=8,
                null=True,
                verbose_name="Cosmic dose rate error (1σ) [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="dose_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Gy/ka",
                max_digits=7,
                null=True,
                verbose_name="Dose rate [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="dose_rate_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Gy/ka, 1σ",
                max_digits=7,
                null=True,
                verbose_name="Dose rate error (1σ) [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="g_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="%/dec",
                max_digits=7,
                null=True,
                verbose_name="g-value [%/dec]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="g_value_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="%/dec",
                max_digits=7,
                null=True,
                verbose_name="g-value error (1σ) [%/dec]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="gamma_dose_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy/ka",
                max_digits=8,
                null=True,
                verbose_name="γ dose rate [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="gamma_dose_rate_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy/ka",
                max_digits=8,
                null=True,
                verbose_name="γ dose rate error (1σ) [Gy/ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="grain_size_max",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Max. grain size [µm]"
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="grain_size_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Min. grain size [µm]"
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="instrumental_beta_source_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=7,
                null=True,
                verbose_name="β source error [%]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="k_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="%",
                max_digits=8,
                null=True,
                verbose_name="K [%]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="k_percent_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="%",
                max_digits=8,
                null=True,
                verbose_name="K error (1σ) [%]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="luminescence_age",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="ka",
                max_digits=10,
                null=True,
                verbose_name="Age [ka]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="od_gy",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Gy",
                max_digits=7,
                null=True,
                verbose_name="OD [Gy]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="od_gy_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Gy",
                max_digits=7,
                null=True,
                verbose_name="OD error (1σ) [Gy]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="od_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="%",
                max_digits=7,
                null=True,
                verbose_name="OD [%]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="od_percent_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="%",
                max_digits=7,
                null=True,
                verbose_name="OD error (1σ) [%]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="palaeodose_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy, 1σ",
                max_digits=10,
                null=True,
                verbose_name="Palaeodose error (1σ) [Gy]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="palaeodose_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Gy",
                max_digits=10,
                null=True,
                verbose_name="Palaeodose [Gy]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="th_ppm",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="ppm",
                max_digits=8,
                null=True,
                verbose_name="Th [ppm]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="th_ppm_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="ppm",
                max_digits=8,
                null=True,
                verbose_name="Th error (1σ) [ppm]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="u_ppm",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="ppm",
                max_digits=8,
                null=True,
                verbose_name="U [ppm]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="u_ppm_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="ppm",
                max_digits=8,
                null=True,
                verbose_name="U error (1σ) [ppm]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="uncertainty_beta_source_calibration",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="β calibration uncertainty [%]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="water_content_for_dating",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="%",
                max_digits=8,
                null=True,
                verbose_name="Water content [%]",
            ),
        ),
        migrations.AlterField(
            model_name="luminescencedating",
            name="water_content_for_dating_error",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="%",
                max_digits=8,
                null=True,
                verbose_name="Water content error (1σ) [%]",
            ),
        ),
    ]
