# Generated by Django 6.0.6 on 2026-06-10 14:45

import analysis.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_grainsize_gravel_grainsize_source_and_more'),
        ('field_data', '0004_alter_location_options_alter_studyarea_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microxrfmeasurement',
            options={'verbose_name': 'MicroXRF', 'verbose_name_plural': 'MicroXRF'},
        ),
        migrations.AlterField(
            model_name='luminescencedating',
            name='year_of_publication',
            field=models.PositiveIntegerField(blank=True, default=analysis.models.current_year, null=True, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.CreateModel(
            name='CosmogenicNuclideDating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('lab_id', models.CharField(blank=True, max_length=30)),
                ('nuclide', models.CharField(blank=True, choices=[('10Be', '¹⁰Be'), ('26Al', '²⁶Al'), ('36Cl', '³⁶Cl'), ('3He', '³He'), ('21Ne', '²¹Ne'), ('14C', 'in-situ ¹⁴C')], max_length=5)),
                ('mineral', models.CharField(blank=True, choices=[('qtz', 'Quartz'), ('fsp', 'Feldspar'), ('px', 'Pyroxene'), ('ol', 'Olivine'), ('cc', 'Calcite'), ('wr', 'Whole rock'), ('other', 'Other')], max_length=10)),
                ('dating_approach', models.CharField(blank=True, choices=[('exposure', 'Exposure dating'), ('burial', 'Burial dating'), ('denudation', 'Denudation rate')], max_length=10)),
                ('nuclide_concentration', models.DecimalField(blank=True, decimal_places=0, help_text='As reported in publication (OCTOPUS: BE10NP / AL26NP)', max_digits=14, null=True, verbose_name='Published concentration [atoms/g]')),
                ('nuclide_concentration_error', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Concentration error (1σ) [atoms/g]')),
                ('ams_standard', models.CharField(blank=True, help_text='e.g. 07KNSTD, KNSTD, NIST_27900 (OCTOPUS: BESTND / ALSTND)', max_length=20, verbose_name='AMS standard')),
                ('normalized_concentration', models.DecimalField(blank=True, decimal_places=0, help_text='Standard-corrected for inter-lab comparison (OCTOPUS: BE10NC / AL26NC)', max_digits=14, null=True, verbose_name='Normalized concentration [atoms/g]')),
                ('normalized_concentration_error', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Normalized concentration error (1σ) [atoms/g]')),
                ('exposure_age', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Exposure age [ka]')),
                ('exposure_age_error_internal', models.DecimalField(blank=True, decimal_places=3, help_text='AMS measurement uncertainty only', max_digits=7, null=True, verbose_name='Internal age error (1σ) [ka]')),
                ('exposure_age_error_external', models.DecimalField(blank=True, decimal_places=3, help_text='Includes production rate uncertainty', max_digits=7, null=True, verbose_name='External age error (1σ) [ka]')),
                ('burial_age', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Burial age [ka]')),
                ('burial_age_error', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Burial age error (1σ) [ka]')),
                ('denudation_rate', models.DecimalField(blank=True, decimal_places=3, help_text='As reported in publication (OCTOPUS: BE10EP / AL26EP)', max_digits=10, null=True, verbose_name='Published denudation rate [mm/ka]')),
                ('denudation_rate_error', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Denudation rate error (1σ) [mm/ka]')),
                ('scaling_method', models.CharField(blank=True, choices=[('LSD', 'LSD / Lifton-Sato-Dunai'), ('LSDn', 'LSDn / Lifton-Sato-Dunai (updated)'), ('St', 'St / Stone'), ('Lm', 'Lm / Lal modified'), ('Du', 'Du / Dunai'), ('De', 'De / Desilets')], max_length=10)),
                ('calculation_software', models.CharField(blank=True, help_text='e.g. CRONUS-Earth, CRONUScalc, CAIRN', max_length=50)),
                ('production_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total production rate [atoms/g/a]')),
                ('production_rate_error', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Production rate error (1σ) [atoms/g/a]')),
                ('spallation_production_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Spallation production rate [atoms/g/a]')),
                ('muon_production_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Muon production rate [atoms/g/a]')),
                ('topographic_shielding', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Topographic shielding (0–1)')),
                ('self_shielding', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Self-shielding (0–1)')),
                ('snow_shielding', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Snow shielding (0–1)')),
                ('combined_shielding', models.DecimalField(blank=True, decimal_places=6, help_text='Product of all shielding and production scaling factors (OCTOPUS: BETOTS / ALTOTS)', max_digits=9, null=True, verbose_name='Combined shielding & scaling correction')),
                ('erosion_rate_assumed', models.DecimalField(blank=True, decimal_places=3, help_text='Steady-state erosion assumption for age calculation', max_digits=7, null=True, verbose_name='Assumed erosion rate [mm/ka]')),
                ('inheritance', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Inheritance [atoms/g]')),
                ('error_ams', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='AMS measurement error')),
                ('error_muon', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Muon production error')),
                ('error_production_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Production rate error')),
                ('error_total', models.DecimalField(blank=True, decimal_places=6, help_text='Quadrature sum of AMS + muon + production rate errors (OCTOPUS: ERRBE_TOT / ERRAL_TOT)', max_digits=12, null=True, verbose_name='Total error (combined)')),
                ('published', models.BooleanField(default=False)),
                ('year_of_publication', models.PositiveIntegerField(blank=True, default=analysis.models.current_year, null=True, validators=[django.core.validators.MinValueValidator(1984), analysis.models.max_value_current_year])),
                ('thesis', models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD'), ('None', 'None')], default='None', max_length=4)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('raw_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cosmogenic_nuclide_datings', to='analysis.rawmeasurement')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cosmogenic_nuclide_datings', to='field_data.sample')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cosmogenic Nuclide Dating',
                'verbose_name_plural': 'Cosmogenic Nuclide Datings',
            },
        ),
    ]
