# Generated by Django 6.0.6 on 2026-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_microxrfmeasurement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cosmogenicnuclidedating',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='luminescencedating',
            name='aliquot_size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='luminescencedating',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='microxrfmeasurement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rawmeasurement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rawprocessing',
            name='processing_description',
            field=models.TextField(blank=True),
        ),
    ]
