# Generated by Django 6.0.6 on 2026-06-10 21:42

from django.db import migrations, models


def fill_null_comments(apps, schema_editor):
    LuminescenceDating = apps.get_model('analysis', 'LuminescenceDating')
    LuminescenceDating.objects.filter(comments__isnull=True).update(comments='')
    CosmogenicNuclideDating = apps.get_model('analysis', 'CosmogenicNuclideDating')
    CosmogenicNuclideDating.objects.filter(comments__isnull=True).update(comments='')


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_microxrfmeasurement_options_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_null_comments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cosmogenicnuclidedating',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='luminescencedating',
            name='aliquot_size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='luminescencedating',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='microxrfmeasurement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rawmeasurement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rawprocessing',
            name='processing_description',
            field=models.TextField(blank=True),
        ),
    ]
