# Generated by Django 6.0.6 on 2026-08-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_algorithm_description_alter_algorithm_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['name', 'version']},
        ),
    ]
