# Generated by Django 6.0.6 on 2026-08-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_alter_algorithm_options'),
        ('field_data', '0015_alter_country_options_alter_province_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmeasurement',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='generic_measurements', to='field_data.sample'),
        ),
        migrations.AlterField(
            model_name='grainsize',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grain_sizes', to='field_data.sample'),
        ),
        migrations.AlterField(
            model_name='microxrfmeasurement',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='microxrf_measurements', to='field_data.sample'),
        ),
    ]
