# Generated by Django 6.0.6 on 2026-08-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_alter_genericmeasurement_sample_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosmogenicnuclidedating',
            options={'ordering': ['-modified_at', '-created_at'], 'verbose_name': 'Cosmogenic Nuclide Dating', 'verbose_name_plural': 'Cosmogenic Nuclide Datings'},
        ),
        migrations.AlterModelOptions(
            name='counting',
            options={'ordering': ['-modified_at', '-created_at'], 'verbose_name': 'Counting', 'verbose_name_plural': 'Countings'},
        ),
        migrations.AlterModelOptions(
            name='grainsize',
            options={'ordering': ['-modified_at', '-created_at'], 'verbose_name_plural': 'Grain size'},
        ),
        migrations.AlterModelOptions(
            name='microxrfmeasurement',
            options={'ordering': ['-modified_at', '-created_at'], 'verbose_name': 'MicroXRF', 'verbose_name_plural': 'MicroXRF'},
        ),
        migrations.AlterModelOptions(
            name='pollen',
            options={'ordering': ['-modified_at', '-created_at'], 'verbose_name': 'Pollen', 'verbose_name_plural': 'Pollen'},
        ),
        migrations.AlterModelOptions(
            name='pollencount',
            options={'ordering': ['-modified_at', '-created_at'], 'verbose_name': 'Pollen Count', 'verbose_name_plural': 'Pollen Counts'},
        ),
    ]
