# Generated by Django 6.0.6 on 2026-08-14 09:35

import analysis.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_alter_cosmogenicnuclidedating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luminescencedating',
            name='year_of_publication',
            field=models.PositiveIntegerField(blank=True, default=analysis.models.current_year, null=True, validators=[django.core.validators.MinValueValidator(1984), analysis.models.max_value_current_year]),
        ),
    ]
