# Generated by Django 6.0.6 on 2026-08-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_alter_luminescencedating_year_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmeasurement',
            name='MeasurementSeries',
            field=models.ForeignKey(blank=True, db_column='MeasurementSeries_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_measurements', to='analysis.measurementseries'),
        ),
        migrations.RenameField(
            model_name='genericmeasurement',
            old_name='MeasurementSeries',
            new_name='measurement_series',
        ),
    ]
