# Generated by Django 6.0.6 on 2026-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_genericmeasurement_measurementseries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luminescencedating',
            name='data_quality',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('questionable', 'Questionable'), ('rejected', 'Rejected'), ('pending', 'Pending review')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='luminescencedating',
            name='quality_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radiocarbondating',
            name='data_quality',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('questionable', 'Questionable'), ('rejected', 'Rejected'), ('pending', 'Pending review')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='radiocarbondating',
            name='quality_note',
            field=models.TextField(blank=True),
        ),
    ]
